name = "wave-analyzer-dashboard"
compatibility_date = "2023-10-30"

# Add this line for Pages deployment
pages_build_output_dir = "dist"

[vars]
ENABLE_MOCK_DATA = "false"
ENABLE_CACHING = "true"

# If you created a KV namespace, include it here
# [[kv_namespaces]]
# binding = "CACHE_STORAGE"
# id = "your-kv-namespace-id"

[site]
bucket = "./dist"  # For your frontend assets

[env.production]
# Your production settings...