name = "wave-analyzer-dashboard"
compatibility_date = "2023-10-30"
pages_build_output_dir = "dist"

[env.production.vars]
VITE_API_BASE_URL = "https://wave-analyzer-dashboard-api.metaversesherpa.workers.dev"