#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "api-backend"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENABLE_MOCK_DATA = "false"
ENABLE_CACHING = "true"

# Enable observability
[observability]
enabled = true

# Explicitly acknowledge the use of secrets
# The TELEGRAM_BOT_TOKEN secret should be set with:
# $ npx wrangler secret put TELEGRAM_BOT_TOKEN

# KV namespace binding - uncomment and add your KV namespace ID when ready
# [[kv_namespaces]]
# binding = "CACHE_STORAGE" 
# id = "YOUR_KV_NAMESPACE_ID"
