#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "api-backend"
main = "worker.js"
compatibility_date = "2024-09-23"  # Updated to resolve URL module issue
compatibility_flags = ["nodejs_compat"]

# Domain configuration using Routes
routes = [
  { pattern = "elliottwaves.ai/api/*", zone_name = "elliottwaves.ai" },
  { pattern = "*.elliottwaves.ai/api/*", zone_name = "elliottwaves.ai" }
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


[vars]
ENABLE_MOCK_DATA = "false"
ENABLE_CACHING = "true"
APP_VERSION = "0.0.9"

# Comment out the KV namespace binding until you have a valid KV namespace ID
# To create a KV namespace, run: npx wrangler kv:namespace create CACHE_STORAGE
# Then update this configuration with the ID from the output
# [[kv_namespaces]]
# binding = "CACHE_STORAGE"
# id = "your-kv-namespace-id-here"
# preview_id = "your-preview-kv-id-here"
