name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm ci
        cd api-backend && npm ci

    - name: Security Audit
      run: |
        npm audit
        cd api-backend && npm audit

    - name: Build
      run: |
        npm run build
        cd api-backend && npm run build

    - name: Test
      run: |
        npm test || true
        cd api-backend && npm test || true
